android-native-changes:
  - changed-files:
      - any-glob-to-any-file: [android/*]
  - head-branch:
      - renovate/capacitor-.*
      - renovate/capawesome-.*
      - renovate/capgo-.*

ios-native-changes:
  - changed-files:
      - any-glob-to-any-file: [ios/*]
  - head-branch:
      - renovate/capacitor-.*
      - renovate/capawesome-.*
      - renovate/capgo-.*
