name: Signaler un bug
description: Signalement d'un bug sur l'appli

type: bug

body:
- type: textarea
  id: reproduction
  validations:
    required: true
  attributes:
    label: Reproduction
    description: Comment reproduire le bug? Donnez les étapes
    placeholder: |
      1. Ouvrir une session
      2. Lancer le recadrage automatique en allant sur l'onglet Recadrer
      3. Ouvrir une photo qui a été inférée, pendant que le recadrage automatique continue
      4. Commencer à modifier le recadrage de la photo
      5. La boîte se remet toute seule à sa position initiale 

- type: upload
  id: screenshots
  validations:
    required: false
  attributes:
    label: Screenshots
    description: Si ça peut aider


- type: textarea
  id: debuginfo
  validations:
    required: false
  attributes:
    label: Contexte
    description: _Rempli automatiquement, normalement_
