name: Notify
description: Send a push notification with ntfy.sh

inputs:
  title:
    required: true
  message:
    required: true
  url:
    description: Where to go when clicking the notification
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl -X POST "https://ntfy.envs.net/cigale"  \
          -H "Title: ${{ inputs.title }}" \
          -H "Click: ${{ inputs.url }}" \
          -H "Priority: Urgent" \
          -H "Icon: https://raw.githubusercontent.com/cigaleapp/cigale/main/static/favicon-96x96.png" \
          -d "${{ inputs.message }}"
