name: Build

env:
  ELECTRON_SKIP_BINARY_DOWNLOAD: 'true'

on:
  workflow_call:
    inputs:
      debug:
        required: false
        type: boolean
        default: true
        description: Build with debug info (non-minified + sourcemaps)
    outputs:
      artifact:
        description: The build artifact name
        value: ${{ jobs.app.outputs.artifact }}

jobs:
  app:
    runs-on: ubuntu-latest
    name: App
    outputs:
      artifact: ${{ steps.artifact.outputs.name }}
    env:
      PR_NUMBER: ${{ github.event.number }}
      BUILD_COMMIT: ${{ github.sha }}
      BUILTIN_PROTOCOLS: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.head_ref || github.ref_name }}/examples/arthropods.cigaleprotocol.json,https://raw.githubusercontent.com/${{ github.repository }}/${{ github.head_ref }}/protocols/insecta.cigaleprotocol.yaml,https://raw.githubusercontent.com/${{ github.repository }}/${{ github.head_ref || github.ref_name }}/protocols/entomoscope.cigaleprotocol.yaml
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Set env vars depending on $PR_NUMBER
        run: |
          # Production builds are deployed to Github Pages
          if [[ -z "$PR_NUMBER" ]]; then
            echo "SVELTE_FALLBACK_PAGE=404.html" >> $GITHUB_ENV
            echo "BASE_PATH=/${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          # PR previews are deployed to a dev server
          else
            echo "SVELTE_FALLBACK_PAGE=index.html" >> $GITHUB_ENV
            echo "BASE_PATH=" >> $GITHUB_ENV
          fi
      - if: inputs.debug
        name: Build
        run: bun run build
      - if: ${{ !inputs.debug }}
        name: Build (without minification)
        run: bun run build
        env:
          DEBUG: 'true'
      - name: Determine artifact name
        id: artifact
        run: echo "name=build-${{ inputs.debug && 'minified' || 'full' }}-${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Upload build as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact.outputs.name }}
          include-hidden-files: true
          path: |
            public
            .svelte-kit
