name: Github Pages

on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
        description: The build artifact name to deploy (output from the build workflow)

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ inputs.artifact }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          folder: public # The folder the action should deploy.
          force: true
          single-commit: true
          clean-exclude: |
            .nojekyll
            _pullrequests
            _playwright
            _vitest
            _coverage
            _nodemodules
            playwright.json
