name: Github Pages

on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
        description: The build artifact name to deploy (output from the build workflow)

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
          force: true
          single-commit: true
          clean-exclude: |
            .nojekyll
            _pullrequests
            _playwright
            _vitest
            _coverage
            _nodemodules
            playwright.json
