name: Docker image

on:
  workflow_call:
    inputs:
      artifact:
        type: string
        description: Name of artifact to download built app from. If empty, app will be built here.
        default: ''
      tag:
        type: string
        description: Tag to apply to the Docker image. Defaults to the GitHub SHA.
        default: ''
      deploy:
        type: boolean
        default: false

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: .bun-version
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - if: inputs.artifact != ''
        name: Download built app
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ inputs.artifact }}
      - if: inputs.artifact == ''
        name: Build
        run: bun run build
      - name: Build docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          file: ./Dockerfile
          context: .
          push: ${{ inputs.deploy }}
          tags: |
            ghcr.io/cigaleapp/cigale:latest
            ghcr.io/cigaleapp/cigale:${{ inputs.tag || github.sha }}
