name: Desktop app

on:
  workflow_call:
    inputs: {}

# https://www.electronforge.io/config/publishers/github#authentication
permissions:
  contents: write

concurrency:
  group: build-electron-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: windows, name: Windows, artifacts: out/make/squirrel.windows/*/*Setup.exe }
          # Disabled for now
          # - { os: macos, name: macOS, artifacts: out/make/ }
          # - { os: ubuntu, name: Linux, artifacts: out/make/ }

    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Node.js
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: .bun-version

      # Install flatpak for Linux builds
      - name: Install flatpak
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build & package app
        run: bun run prebuild; bunx electron-forge make
        env: { ELECTRON_BUILD: '1' }
      - name: see output
        uses: jaywcjlove/github-action-folder-tree@8888262a56c33d3849154fa1fb7355c2465da30c # main
        with:
          path: .vite
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: cigale-desktop-${{ matrix.os }}
          path: ${{ matrix.artifacts }}
