name: Android E2E tests

permissions:
  actions: write
  contents: read
  pull-requests: write

on:
  workflow_call:
    secrets:
      DEV_DEPLOYMENTS_SSH_PRIVATE_KEY:
        required: true
        description: 'SSH private key for deploying to dev deployments server'
      PLEYE_API_KEY:
        required: false
        description: 'API key for uploading test results to Pleye'
      HUGGINGFACE_ACCESS_TOKEN:
        required: true
        description: Access token for the Huggingface Hub API. Used to pre-download models from Huggingface. Shouldn't need any specific permissions, as repos it downloads files from are public.
    inputs:
      artifact:
        type: string
        description: Name of artifact to download built app from.
        required: true
      env:
        type: string
        description: |
          Additional environments variables when runnning tests. 
          Syntax is NAME1=value1 NAME2=value2 ...

          Useful variables:
          - DEBUG_WORKERS=true: show logs when web workers are created/closed
        required: false
        default: ''
    outputs:
      total:
        value: ${{ jobs.combine-reports.outputs.total }}
        description: Total number of tests than ran
      failed:
        value: ${{ jobs.combine-reports.outputs.failed }}
        description: Failed tests count
      flaky:
        value: ${{ jobs.combine-reports.outputs.flaky }}
        description: Flaky tests count
      successful:
        value: ${{ jobs.combine-reports.outputs.successful }}
        description: Successful tests count
      skipped:
        value: ${{ jobs.combine-reports.outputs.skipped }}
        description: Skipped tests count

env:
  ELECTRON_SKIP_BINARY_DOWNLOAD: 'true'
  PLEYE_DEBUG: nodebug
  PLEYE_API_KEY: ${{ secrets.PLEYE_API_KEY }}
  PR_NUMBER: ${{ github.event.number }}
  COMMIT_SHA: ${{  github.event.pull_request.head.sha || github.sha }}
  # XXX: Depends on dev-deployments workflow's domain default value
  TRACE_VIEWER_BASE_URL: https://pr-${{ github.event.number }}-reports.cigale.gwen.works/playwright

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 3
          
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .bun-version
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      
      - name: Download built app
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.artifact }}
          path: ./
          
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1

      - name: Sync capacitor
        run: bun cap sync
        
      - name: Run test on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          working-directory: ./android
          target: google_apis_playstore
          arch: x86_64
          ram-size: 8192M
          script: |
            chmod +x ./gradlew
            ./gradlew :app:connectedNightlyDebugAndroidTest --stacktrace --info
