name: Android E2E tests

permissions:
  actions: write
  contents: read
  pull-requests: write

on:
  workflow_call:
    secrets:
      DEV_DEPLOYMENTS_SSH_PRIVATE_KEY:
        required: true
        description: 'SSH private key for deploying to dev deployments server'
      PLEYE_API_KEY:
        required: false
        description: 'API key for uploading test results to Pleye'
      HUGGINGFACE_ACCESS_TOKEN:
        required: true
        description: Access token for the Huggingface Hub API. Used to pre-download models from Huggingface. Shouldn't need any specific permissions, as repos it downloads files from are public.
    inputs:
      artifact:
        type: string
        description: Name of artifact to download built app from.
        required: true
      env:
        type: string
        description: |
          Additional environments variables when runnning tests. 
          Syntax is NAME1=value1 NAME2=value2 ...

          Useful variables:
          - DEBUG_WORKERS=true: show logs when web workers are created/closed
        required: false
        default: ''
    outputs:
      total:
        value: ${{ jobs.combine-reports.outputs.total }}
        description: Total number of tests than ran
      failed:
        value: ${{ jobs.combine-reports.outputs.failed }}
        description: Failed tests count
      flaky:
        value: ${{ jobs.combine-reports.outputs.flaky }}
        description: Flaky tests count
      successful:
        value: ${{ jobs.combine-reports.outputs.successful }}
        description: Successful tests count
      skipped:
        value: ${{ jobs.combine-reports.outputs.skipped }}
        description: Skipped tests count

env:
  ELECTRON_SKIP_BINARY_DOWNLOAD: 'true'
  PLEYE_DEBUG: nodebug
  PLEYE_API_KEY: ${{ secrets.PLEYE_API_KEY }}
  PR_NUMBER: ${{ github.event.number }}
  COMMIT_SHA: ${{  github.event.pull_request.head.sha || github.sha }}
  # XXX: Depends on dev-deployments workflow's domain default value
  TRACE_VIEWER_BASE_URL: https://pr-${{ github.event.number }}-reports.cigale.gwen.works/playwright

jobs:
  predownload:
    runs-on: ubuntu-latest
    name: Pre-download models
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .bun-version

      - name: Get list of model URLs
        id: models
        run: |
          urls=$(jq -r "[$JQ_SELECTORS] | join(\" \")" examples/arthropods.cigaleprotocol.json)
          echo "urls=$urls" >> $GITHUB_OUTPUT

          huggingface_repos=""
          non_huggingface_urls=""
          for url in $urls; do
            if echo $url | grep -q 'huggingface.co'; then
              repo=$(echo $url | sed -E 's#https://huggingface.co/([^/]+/[^/]+)/.+#\1#')
              huggingface_repos="$huggingface_repos $repo"
            else
              non_huggingface_urls="$non_huggingface_urls $url"
            fi
          done

          huggingface_repos=$(printf '%s\n' $huggingface_repos | sort -u | tr '\n' ' ')

          echo "huggingface-repos=$huggingface_repos" >> $GITHUB_OUTPUT
          echo "non-huggingface-urls=$non_huggingface_urls" >> $GITHUB_OUTPUT
        env:
          JQ_SELECTORS: .metadata[].infer?.neural[]?.model,
            .metadata[].infer?.neural[]?.classmapping | select(. | type | match("string"))

      - name: Compute cache key
        id: caching
        env:
          hf_token: ${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}
        run: |
          key=""
          for repo in ${{ steps.models.outputs.huggingface-repos }}; do
            echo "Getting latest commit hash for $repo"
            hash=$(curl --header "Authorization: Bearer $hf_token" -s "https://huggingface.co/api/models/$repo/commits/main?limit=1" | jq -r '.[0].id')
            key+="$repo@$hash;"
          done

          for url in ${{ steps.models.outputs.non-huggingface-urls }}; do
            key+="$url;"
          done

          echo "Computed cache key: $key"

          echo "key=predownloaded-models:$key" >> $GITHUB_OUTPUT

      - name: Use cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: ${{ steps.caching.outputs.key }}
          path: |
            *.onnx
            *-classmapping.txt

      - name: Pre-download default protocol's models
        run: |
          for url in ${{ steps.models.outputs.urls }}; do
            if [ -f "$(basename $url)" ]; then
              echo "File for $url already exists, skipping download"
              continue
            fi
            echo "Downloading $url"
            wget --content-disposition -q $url
          done

      - name: Save to artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: predownloaded-models
          path: |
            *.onnx
            *-classmapping.txt

  test:
    timeout-minutes: 60
    runs-on: macos-latest
    name: Test
    needs: predownload
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 3
          
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .bun-version
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      
      - name: Download built app
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.artifact }}
          path: ./
          
      - name: Retrieve pre-downloaded models
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: predownloaded-models
          
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1

      - name: Sync capacitor
        run: bun cap sync
        
      - name: Run test on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          working-directory: ./android
          target: google_apis_playstore
          ram-size: 8192M
          script: |
            adb devices -l
            adb shell getprop ro.build.version.sdk
            adb shell getprop ro.product.cpu.abi
            adb shell settings get global animator_duration_scale
            adb shell settings get global window_animation_scale
            adb shell settings get global transition_animation_scale
          
            chmod +x ./gradlew
            ./gradlew :app:connectedNightlyDebugAndroidTest --stacktrace --info
