name: Time spent

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, closed]
  push:
    branches: [main]
    paths:
      - .github/workflows/issue-time-worked.yml
      - scripts/github-issue-set-time-worked.ts
  schedule:
    # Run at end of work hours for morning & afternoon
    - cron: '0 12 * * *'
      timezone: Europe/Paris
    - cron: '0 19 * * *'
      timezone: Europe/Paris

jobs:
  compute:
    name: Compute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .bun-version
      - name: Run script
        run: bun scripts/github-issue-set-time-worked.ts
        env:
          WAKATIME_API_KEY: ${{ secrets.GWENNLBH_WAKATIME_API_KEY }}
          WAKATIME_PROJECT: cigale
          GH_TOKEN: ${{ github.token }}
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          EXTRA_PROJECTS:
            | # Format is <cigale branch>:<other wakatime project name>@<other wakatime project's branch>
            generic-binary-storage:idb-opfs@master
            generic-binary-storage:playwright@storagestate-opfs
            fix-exif-orientation2:exiv2-wasm@main
            parallelworkers:swarpc@loadbalancer
            offthread:swarpc@main
