name: Build bun-compatible Playwright Docker image

on:
  pull_request:
    paths:
      - .github/workflows/playwright.dockerfile
      - .github/workflows/playwright-docker-image.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          file: .github/workflows/playwright.dockerfile
          push: true
          tags: ghcr.io/cigaleapp/cigale/playwright-bun:latest
