name: End-to-end tests

permissions:
  actions: write
  contents: read
  pull-requests: write

on:
  workflow_call:
    secrets:
      DEV_DEPLOYMENTS_SSH_PRIVATE_KEY:
        required: true
        description: 'SSH private key for deploying to dev deployments server'
      PLEYE_API_KEY:
        required: false
        description: 'API key for uploading test results to Pleye'
    inputs:
      artifact:
        type: string
        description: Name of artifact to download built app from.
        required: true
      env:
        type: string
        description: |
          Additional environments variables when runnning tests. 
          Syntax is NAME1=value1 NAME2=value2 ...

          Useful variables:
          - DEBUG_WORKERS=true: show logs when web workers are created/closed
        required: false
        default: ''

env:
  ELECTRON_SKIP_BINARY_DOWNLOAD: 'true'
  PLEYE_DEBUG: nodebug
  PLEYE_API_KEY: ${{ secrets.PLEYE_API_KEY }}
  PR_NUMBER: ${{ github.event.number }}
  COMMIT_SHA: ${{  github.event.pull_request.head.sha || github.sha }}
  # XXX: Depends on dev-deployments workflow's domain default value
  TRACE_VIEWER_BASE_URL: https://pr-${{ github.event.number }}-reports.cigale.gwen.works/playwright

jobs:
  predownload:
    runs-on: ubuntu-latest
    name: Pre-download models
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Get list of model URLs
        id: models
        run: |
          urls=$(jq -r "[$JQ_SELECTORS] | join(\" \")" examples/arthropods.cigaleprotocol.json)
          echo "urls=$urls" >> $GITHUB_OUTPUT

          huggingface_repos=""
          non_huggingface_urls=""
          for url in $urls; do
            if echo $url | grep -q 'huggingface.co'; then
              repo=$(echo $url | sed -E 's#https://huggingface.co/([^/]+/[^/]+)/.+#\1#')
              huggingface_repos="$huggingface_repos $repo"
            else
              non_huggingface_urls="$non_huggingface_urls $url"
            fi
          done

          huggingface_repos=$(printf '%s\n' $huggingface_repos | sort -u | tr '\n' ' ')

          echo "huggingface-repos=$huggingface_repos" >> $GITHUB_OUTPUT
          echo "non-huggingface-urls=$non_huggingface_urls" >> $GITHUB_OUTPUT
        env:
          JQ_SELECTORS: .metadata[].infer?.neural[]?.model,
            .metadata[].infer?.neural[]?.classmapping

      - name: Compute cache key
        id: caching
        run: |
          key=""
          for repo in ${{ steps.models.outputs.huggingface-repos }}; do
            echo "Getting latest commit hash for $repo"
            hash=$(curl -s "https://huggingface.co/api/models/$repo/commits/main?limit=1" | jq -r '.[0].id')
            key+="$repo@$hash;"
          done

          for url in ${{ steps.models.outputs.non-huggingface-urls }}; do
            key+="$url;"
          done

          echo "Computed cache key: $key"

          echo "key=predownloaded-models:$key" >> $GITHUB_OUTPUT

      - name: Use cache
        uses: actions/cache@v5
        with:
          key: ${{ steps.caching.outputs.key }}
          path: |
            *.onnx
            *-classmapping.txt

      - name: Pre-download default protocol's models
        run: |
          for url in ${{ steps.models.outputs.urls }}; do
            if [ -f "$(basename $url)" ]; then
              echo "File for $url already exists, skipping download"
              continue
            fi
            echo "Downloading $url"
            wget --content-disposition -q $url
          done

      - name: Save to artifact
        uses: actions/upload-artifact@v7
        with:
          name: predownloaded-models
          path: |
            *.onnx
            *-classmapping.txt

  test:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    name: Test (shard ${{ matrix.shard-index }} of ${{ matrix.shard-count }})
    needs: predownload
    container:
      image: ghcr.io/gwennlbh/playwright-bun:v1.59.1
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        shard-index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
        shard-count: [16]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Download built app
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact }}
          path: ./
      - name: Retrieve pre-downloaded models
        uses: actions/download-artifact@v8
        with:
          name: predownloaded-models
      - name: Remove task-type spec files for better sharding balance
        run: rm tests/tasks/*
      - name: Initialize empty metrics.json (in case no tests wrote it in this shard)
        run: echo "[]" > metrics.json
      - name: Run Playwright tests
        run: ${{ inputs.env }} bunx playwright test --shard=${{ matrix.shard-index}}/${{ matrix.shard-count }}
        env:
          SHARDING: '1'
          JOB_ID: ${{ job.check_run_id }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-shard-${{ matrix.shard-index }}
          path: blob-report/
          retention-days: 30
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: performance-metrics-${{ matrix.shard-index }}
          path: metrics.json
          retention-days: 30

  combine-reports:
    runs-on: ubuntu-latest
    needs: test
    # run even if tests fail
    if: always()
    name: Combine reports
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          path: ./playwright-report-shards
          pattern: playwright-report-shard-*
          merge-multiple: true

      - uses: actions/download-artifact@v8
        with:
          path: ./performance-metrics
          pattern: performance-metrics-*
          merge-multiple: false

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Merge performance metrics
        run: |
          # Merge all performance-metrics-*.json files into one metrics.json
          bun run - <<'EOS'
            import { Glob } from 'bun';

            // Get all performance-metrics-*.json files
            const result = []
            const metrics = new Glob('./performance-metrics/**/metrics.json')

            for await (const filepath of metrics.scan()) {
              const content = await Bun.file(filepath).text()

              try {
                const json = JSON.parse(content)
                if (Array.isArray(json)) {
                  result.push(...json)
                } else {
                  console.warn(`File ${filepath} does not contain an array, skipping:`, json)
                }
              } catch (e) {
                console.error(`Error parsing JSON from file ${filepath}:`, e)
              }
            }

            // Write the merged results to a single metrics.json file
            await Bun.file('./metrics.json').write(JSON.stringify(result))
          EOS

      - name: Merge sharded reports into HTML
        run: bunx playwright merge-reports --reporter html ./playwright-report-shards
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Put metrics.json alongside report for dev-deployments workflow to pick up
        run: mv metrics.json playwright-report/metrics.json

      - name: Save report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: report
          path: ./playwright-report
          retention-days: 1

  upload-report:
    # run even if tests fail
    if: always()
    name: Upload report
    needs: combine-reports
    uses: ./.github/workflows/dev-deploy.yml
    secrets: inherit
    with:
      environment: '#${{ github.event.number }}: E2E tests'
      artifact: report
      subdomain: pr-${{ github.event.number }}-reports
      path: /playwright
      # #?show-metadata-other allows showing extra metadata sections in the report
      # Ref: https://github.com/microsoft/playwright/blob/e76ca6c/packages/html-reporter/src/metadataView.tsx#L62
      environment-url-append: '#?show-metadata-other'

  compare-performance-with-main:
    if: always() && github.event_name == 'pull_request'
    name: Compare performance with main branch
    needs: combine-reports
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Get head branch metrics
        uses: actions/download-artifact@v8
        with:
          name: report
          path: ./head-report

      - name: Get base branch metrics
        run: |
          curl -sSL https://pr--reports.cigale.gwen.works/playwright/metrics.json > base-metrics.json

      - name: Compare metrics
        id: comparison
        run: |
          bun run - <<'EOS'
            const logos = {
              chromium: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Google_Chrome_icon_%28February_2022%29.svg/3840px-Google_Chrome_icon_%28February_2022%29.svg.png",
              webkit: "https://upload.wikimedia.org/wikipedia/fr/thumb/b/be/WebKit_logo_%282015%29.svg/1280px-WebKit_logo_%282015%29.svg.png",
            }

            const logo = (name) => logos[name] ? `<img src="${logos[name]}" alt="${name}" width="32" height="32">` : name;

            const abbreviations = {
              total: "Total",
              domCompleteTiming: "DOM",
              pageloadTiming: "Load",
              totalBytes: "Bytes",
              largestContentfulPaint: "LCP",
              totalBlockingTime: "TBT",
              cumulativeLayoutShift: "CLS",
            }

            const abbr = (metric) => abbreviations[metric] ?? metric

            const headMetrics = await Bun.file('./head-report/metrics.json').text()
              .then(contents => JSON.parse(contents))
              .catch((err) => {
                console.error(`Error parsing head metrics from file ./head-report/metrics.json:`, err);
                return [];
              })

            const baseMetrics = await Bun.file('./base-metrics.json').text()
              .then(contents => JSON.parse(contents))
              .catch((err) => {
                console.error(`Error parsing base metrics from file ./base-metrics.json:`, err);
                return [];
              })

            let comment = "## Performance changes with [`main`](https://github.com/${{ github.repository }}/tree/main)\n\n"

            // Prepare markdown table for sticky PR comment message
            comment += '| Browser | Test | Metric | Head | Base | Change |\n';
            comment += '| ------- | ---- | --- | --- | --- | --- |\n';

            const byTitle = {
              head: Map.groupBy(headMetrics, m => m.title),
              base: Map.groupBy(baseMetrics, m => m.title),
            } 

            let previousBrowser = null;
            let previousTest = null;

            for (const [title, head] of byTitle.head.entries()) {
              const { test, browser, metric, unit } = head[0]
              const base = byTitle.base.get(title)

              const avg = (branch) => branch.reduce((sum, m) => sum + m.value, 0) / branch.length;

              const fmt = (value) => new Intl.NumberFormat('fr-FR', { 
                style: unit ? 'unit' : 'decimal',
                unit: unit || undefined,
                maximumFractionDigits: 2 
              }).format(value);

              const browserIfDiffers = browser === previousBrowser ? '' : browser;
              const testIfDiffers = test === previousTest && browser === previousBrowser ? '' : test;

              const column = (...fields) => '| ' + [
                logo(browserIfDiffers),
                testIfDiffers, 
                abbr(metric), 
                ...fields
              ].join(' | ') + ' |\n';

              if (base) {
                const change = avg(head) - avg(base);
                const trend = change>0 ? '🔺+' : (change<0 ? '🔻' : '');
                comment += column(fmt(avg(head)), fmt(avg(base)), trend + fmt(change));
              } else {
                comment += column(fmt(avg(head)), 'N/A', 'N/A');
              }

              previousBrowser = browser;
              previousTest = test;
            }
            comment += "\n\n"

            comment += "<small>"
            for (const [expansion, abbreviation] of Object.entries(abbreviations)) {
              comment += `${abbreviation}: \`${expansion}\`, `
            }
            comment += "</small>"

            // Write to $GITHUB_OUTPUT to pass to next step
            const output = Bun.file(process.env.GITHUB_OUTPUT);
            await output.write(`comment<<EOF\n${comment}\nEOF\n`);
          EOS

      - name: Post comment to PR
        uses: marocchino/sticky-pull-request-comment@v3.0.4
        with:
          header: ⚡ Performance changes
          message: ${{ steps.comparison.outputs.comment }}
