name: Example protocols

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: 0 0 * * 1,4
  workflow_dispatch:
  pull_request:
    paths:
      - scripts/generate-protocols.js
      - scripts/add-species-from-jessica-joachim.ts
      - scripts/add-species-from-google-slides.js
      - scripts/add-taxonomic-parents-from-gbif.js
      - scripts/add-metadata-from-xper3.ts
      - .github/workflows/protocols.yml
  push:
    branches:
      - renovate/googleapis-*
      - renovate/google-auth-library-*
      - renovate/rss-parser-*
      - renovate/jsdom-*
      - renovate/tinyexec-*
      - renovate/pdf-to-png-converter-*
      - renovate/odt2html-*
      - renovate/turndown-*
      - renovate/marked-*

concurrency:
  group: regenerate-example-protocols
  cancel-in-progress: true

jobs:
  check:
    name: Skip?
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ !steps.changes.outputs.any_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Compute changes with last push
        id: changes
        uses: tj-actions/changed-files@v47.0.5
        with:
          since_last_remote_commit: true
          # XXX: Duplicated from on.pull_request.paths
          files: |
            scripts/generate-protocols.js
            scripts/add-species-from-jessica-joachim.ts
            scripts/add-species-from-google-slides.js
            scripts/add-taxonomic-parents-from-gbif.js
            scripts/add-metadata-from-xper3.ts
            .github/workflows/protocols.yml

      - name: Log summary to list changed files
        run: |
          echo "Changed files: ${{ steps.changes.outputs.all_changed_files }}" >> $GITHUB_STEP_SUMMARY
          echo "Any changed: ${{ steps.changes.outputs.any_changed }}"  >> $GITHUB_STEP_SUMMARY

  regenerate:
    needs: check
    if: github.event.pull_request.draft == false && needs.check.outputs.skip != 'true'
    name: Regenerate
    runs-on: ubuntu-latest

    steps:
      - name: Check runs titles
        id: checkruns
        env: 
          runs: |
            init          Initialize
            xper3         Xper3
            jj-species    JJ Species
            google-slides Google Slides
            gbif          GBIF
            jj-genus      JJ Genus
            finalize      Finalize
          query: >
            split("\n")
            | map(select(length > 0))
            | map(split(" ") | {
              id: .[0], 
              name: "Example protocols / Regenerate: " + (.[1:] | join(" ") | trim)
            })
        run: |
          {
            echo "runs<<EOF"
            echo "$runs" | jq "$query" 
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Setup check runs
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          status: queued
          checks: ${{ steps.checkruns.outputs.runs }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.AUTOCOMMITS_DEPLOY_KEY }}

      - name: Setup Node.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: init
          status: in_progress

      - name: Initialize protocol
        run: bun run scripts/generate-protocols.js

      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: init
          conclusion: success
          
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: xper3
          status: in_progress

      - name: Add metadata from Xper3
        run: bun run scripts/add-metadata-from-xper3.ts

      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: xper3
          conclusion: success

      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: jj-species
          status: in_progress

      - name: Add species descriptions from JJ
        run: bun run scripts/add-species-from-jessica-joachim.ts species
        env:
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}


      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: jj-species
          conclusion: success
          
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: google-slides
          status: in_progress

      - name: Set google-drive-key.json
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.GOOGLE_DRIVE_KEY_BASE64 }}
          filename: google-drive-key.json
          is-executable: false
          working-directory: ./

      - name: Add data from Google Slides folder
        run: bun run scripts/add-species-from-google-slides.js

      - name: Unset google-drive-key.json
        run: rm google-drive-key.json

      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: google-slides
          conclusion: success
          
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: gbif
          status: in_progress

      - name: Add data from GBIF
        run: bun run scripts/add-taxonomic-parents-from-gbif.ts


      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: gbif
          conclusion: success
          
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: jj-genus
          status: in_progress

      - name: Add genus descriptions from JJ
        run: bun run scripts/add-species-from-jessica-joachim.ts genus
        env:
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}

      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: jj-genus
          conclusion: success
          
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: finalize
          status: in_progress

      - name: Clean old protocol
        run: rm examples/old-*.json

      - name: Format generated protocols
        run: bun x prettier --write examples/*.cigaleprotocol.json

      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: finalize
          conclusion: success
          
      - uses: dflydev/check-runs-action@v1
        with:
          token: ${{ github.token }}
          id: xper3
          status: in_progress

      - name: Setup diffing that ignores version and learnMore fields
        run: git config diff.example-protocols.textconv "$textconv"
        env:
          textconv: jq 'del(.version) | del(.learnMore)' $1

      - name: Pull in case main has changed since we started
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: git pull origin main --rebase --autostash

      - name: Check for changes
        id: status
        run: |
          git diff || true
          echo "changed=$(git diff --quiet && echo false || echo true)" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.status.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 🍱 Regenerate example protocols
          file_pattern: examples/*.cigaleprotocol.json examples/*.cigaleprotocol.images/*
