name: Update README screenshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,4' # Runs at 00:00 UTC every Monday and Thursday

jobs:
  update-readme-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.21'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright readme.spec.js and update screenshots
        run: bunx playwright test tests/tasks/readme.spec.js --update-snapshots
        env:
          RUN_README_TESTS: '1'

      - name: Remove test-results.json
        run: rm test-results.json || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: '📝 Update README screenshots'
          title: '📝 Update README screenshots'
          body: |
            This PR was automatically generated by the [update-readme-snapshots workflow](https://${{ github.repository }}/blob/${{ github.sha }}/.github/workflows/update-readme-snapshots.yml).
          branch: update-readme-snapshots
          base: main
