name: Regenerate arthropods protocol

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  generate-arthropods-protocol:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate taxonomy
        run: npx node scripts/jessica-joachim-crawler.js

      - name: Store scripts/jessica-joachim-crawler-report.md
        id: get-report
        run: |
          touch scripts/jessica-joachim-crawler-report.md
          {
            echo 'report<<EOF'
            cat scripts/jessica-joachim-crawler-report.md
            echo 
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 🍱 Regenerate arthropods protocol
          title: 🍱 Regenerate arthropods protocol
          branch: regen-arthropods-protocol/${{ github.run_number }}
          body: |
            This PR was automatically generated by the [regen-arthropods-protocol workflow](/.github/workflows/regen-arthropods-protocol.yml).

            ## Report for potential missing descriptions

            ${{ steps.get-report.outputs.report }}
