name: Regenerate arthropods protocol

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1,4'
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  generate-arthropods-protocol:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Initialize protocol
        run: npx node scripts/generate-protocols.js

      - name: Add data from Jessica Joachim
        run: npx node scripts/add-species-from-jessica-joachim.js

      - name: Set google-drive-key.json
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.GOOGLE_DRIVE_KEY_BASE64 }}
          filename: google-drive-key.json
          is-executable: false
          working-directory: ./

      - name: Add data from Google Slides folder
        run: npx node scripts/add-species-from-google-slides.js

      - name: Unset google-drive-key.json
        run: rm google-drive-key.json

      - name: Add data from GBIF
        run: npx node scripts/add-taxonomic-parents-from-gbif.js

      - name: Clean old protocol
        run: rm examples/old-*.json

      - name: Store scripts/jessica-joachim-crawler-report.md
        id: get-report
        run: |
          touch scripts/jessica-joachim-crawler-report.md
          {
            echo 'report<<EOF'
            cat scripts/jessica-joachim-crawler-report.md
            echo 
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Format & lintfix
        run: npm run format && npm run lintfix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 🍱 Regenerate arthropods protocol
          title: 🍱 Regenerate arthropods protocol
          branch: regen-arthropods-protocol
          body: |
            This PR was automatically generated by the [regen-arthropods-protocol workflow](https://${{ github.repository }}/blob/${{ github.sha }}/.github/workflows/regen-arthropods-protocol.yml).

            ## Report for potential missing descriptions

            ${{ steps.get-report.outputs.report }}
