on:
  workflow_dispatch:
    inputs:
      title:
        type: string
        default: Test
      message:
        type: string
        default: Example body
      url:
        type: string
        default: https://example.com

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Push notification
        uses: ./.github/actions/notify
        with:
          title: ${{ inputs.title }}
          message: ${{ inputs.message }}
          url: ${{ inputs.url }}
